In [27]:
# !pip install -U scikit-learn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from pandas.core.common import random_state
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [5]:
df = pd.read_csv('Salary_Data.csv')

In [16]:
x = df.iloc[:, :1]
y = df.iloc[:, 1:2]

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state =0)

In [25]:
regressor = LinearRegression()

regressor.fit(x_train, y_train)
regressor.score(x_test,y_test)


0.988169515729126

In [29]:
regressor.coef_

array([[9312.57512673]])

In [30]:
regressor.intercept_

array([26780.09915063])

In [28]:
y_pred = regressor.predict(x_test)


r2 = r2_score(y_test, y_pred) 
mse = mean_squared_error(y_test, y_pred) 
rmse = np.sqrt(mse) 
mae = mean_absolute_error(y_test, y_pred)


print(f"R² Score: {r2:.4f}") 
print(f"MSE: {mse:.4f}") 
print(f"RMSE: {rmse:.4f}") 
print(f"MAE: {mae:.4f}")

R² Score: 0.9882
MSE: 12823412.2981
RMSE: 3580.9792
MAE: 2446.1724


In [32]:
print(y_pred)

[[ 40748.96184072]
 [122699.62295594]
 [ 64961.65717022]
 [ 63099.14214487]
 [115249.56285456]
 [107799.50275317]]


In [35]:
print(x_test)

    YearsExperience
2               1.5
28             10.3
13              4.1
10              3.9
26              9.5
24              8.7
